export const TransactionActions = {
  ITEM_ADD: 'ITEM_ADD',
  ITEM_UPDATE: 'ITEM_UPDATE',
  ITEM_DELETE: 'ITEM_DELETE',
  UNDO_DELETE: 'UNDO_DELETE',
  HEADER_UPDATE: 'HEADER_UPDATE',
  PAYMENT_UPDATE: 'PAYMENT_UPDATE',
  CALCULATE_TOTALS: 'CALCULATE_TOTALS',
  CLEAR_DRAFT: 'CLEAR_DRAFT',
  RESET: 'RESET',
  SET_DRAFT: 'SET_DRAFT'
};
